name = "engageengine-sprint"
main = "src/worker.js"
compatibility_date = "2026-06-08"

[[d1_databases]]
binding = "DB"
database_name = "command-center"
database_id = "13f98f2a-574d-495c-acd7-4f8900acd036"
