-- EngageEngine Client Operating Routine — Sprint Tracker seed
DELETE FROM sprint_template_tasks WHERE template_id LIKE 'rt-%';
DELETE FROM sprint_templates WHERE id LIKE 'rt-%';
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-p0-onboard','P0 · Onboarding','Lifecycle',10,'once','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t01','rt-p0-onboard','Send onboarding wizard link + intake form to client','Staff',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t02','rt-p0-onboard','Request/verify GA4 + Google Ads access (goes to marketingperformancemcc@gmail.com)','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t03','rt-p0-onboard','Verify Google Search Console access (add user or DNS TXT) — REQUIRED before SEO baseline','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t04','rt-p0-onboard','Verify Google Business Profile manager access','Staff',4,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t05','rt-p0-onboard','Verify Meta ad account + Page access','Staff',5,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t06','rt-p0-onboard','Set up client in Vendasta + run the Snapshot Report (feeds Phase 1 baseline)','Staff',6,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t07','rt-p0-onboard','Add paid Vendasta modules per the client''s retainer tier','Staff',7,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t08','rt-p0-onboard','Add client to the 30-Day Sprint (status Active)','Staff',8,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t09','rt-p0-onboard','Add client to Services page canonical list + set service flags on','Staff',9,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t10','rt-p0-onboard','Write ALL new IDs/keys to the Credentials Index (same session)','Robbie',10,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t11','rt-p0-onboard','Register client in clients.json, CLAUDE.md registry, and Second Brain','Robbie',11,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p0-onboard-t12','rt-p0-onboard','GATE: confirm every access box is green before starting Phase 1','Robbie',12,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-p1-baseline','P1 · Baseline & Diagnose','Lifecycle',20,'once','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t01','rt-p1-baseline','Read the Vendasta Snapshot first — it frames the whole diagnosis','Robbie',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t02','rt-p1-baseline','Run GBP baseline analysis (profile health, calls/directions/website-clicks, review velocity)','Staff',2,'gbp');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t03','rt-p1-baseline','Run DVS — Demand Visibility Score (AI-era visibility + retrievability)','Staff',3,'dvs');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t04','rt-p1-baseline','Run /demand-collapse-diagnostic — core ''what''s broken'' read','Robbie',4,'dcd');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t05','rt-p1-baseline','Run /ads-audit if inheriting an existing Google Ads account','Staff',5,'ads-audit');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t06','rt-p1-baseline','Run /toprank:seo-analysis — SEO baseline (needs GSC connected)','Staff',6,'seo_analysis');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t07','rt-p1-baseline','Run /page-cro on the money/landing pages','Staff',7,'page-analyzer');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p1-baseline-t08','rt-p1-baseline','Assemble the internal diagnostic doc → the campaign plan comes from THIS','Robbie',8,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-p2-build','P2 · Build & Launch','Lifecycle',30,'once','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t01','rt-p2-build','Build campaigns (Google/Meta) per the plan','Staff',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t02','rt-p2-build','Install/verify pixel + conversion tracking','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t03','rt-p2-build','Wire form → conversion event — DO NOT launch until it fires','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t04','rt-p2-build','Turn on the intent pipeline (audience → Meta targeting + Vendasta CRM)','Staff',4,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t05','rt-p2-build','Stand up Vendasta social calendar; connect profiles; enable auto-post to client GBP','Creative',5,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t06','rt-p2-build','Provision portal / deliverables hub if the client gets one','Staff',6,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-p2-build-t07','rt-p2-build','GATE: confirm the conversion fires before any spend goes live','Robbie',7,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-seo','SEO Track','Monthly',40,'monthly','seo',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t01','rt-seo','Re-pull GSC + rankings; diff vs baseline (what moved, what''s stuck)','Staff',1,'seo_analysis');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t02','rt-seo','Check & pull new articles/reports from the desktop SEO tool','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t03','rt-seo','Send SEO article/deliverable for client approval','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t04','rt-seo','On approval → post to the client website','Staff',4,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t05','rt-seo','Report SEO progress to client (what published + ranking impact)','Staff',5,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t06','rt-seo','Extract recommendations → ticket the implementation work','Staff',6,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-seo-t07','rt-seo','Implement fixes; verify they landed next cycle (Implementation Rule)','Staff',7,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-social','Social Track','Weekly',50,'weekly','social',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-social-t01','rt-social','Build/refresh the social calendar in Vendasta','Creative',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-social-t02','rt-social','Route the calendar for CLIENT approval (Robbie approves too, depending on client)','Robbie',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-social-t03','rt-social','Publish approved posts (including to client GBP)','Creative',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-social-t04','rt-social','Verify GBP posting actually succeeded','Staff',4,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-social-t05','rt-social','Log reviews / reputation activity for the weekly check','Staff',5,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-cro','CRO · 45-Day Pass','45-Day',60,'45day','website',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-cro-t01','rt-cro','Run /page-cro on the primary money pages','Staff',1,'page-analyzer');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-cro-t02','rt-cro','Run /form-cro on the lead forms','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-cro-t03','rt-cro','Ticket + implement the CRO fixes','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-cro-t04','rt-cro','Verify changes are live + measure the lift','Staff',4,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-ads','Ads Management','Monthly',70,'monthly','gads,meta',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-ads-t01','rt-ads','Run /ads-audit (30-day + MoM comparison)','Staff',1,'ads-audit');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-ads-t02','rt-ads','Action quick wins the same week (negatives, budget, bids)','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-ads-t03','rt-ads','Ticket the bigger structural changes','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-ads-t04','rt-ads','Verify no conversion-tracking regressions after changes','Staff',4,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-daily','Daily Ops (all clients)','Daily',80,'daily','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-daily-t01','rt-daily','Run `/adcheck top` daily (top-spender Google Ads pulse); full `/adcheck` sweep (all clients + Meta + GA4) Mon/Wed/Fri — act on flags only','Staff',1,'adcheck');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-daily-t02','rt-daily','Run /morning inbox sweep → today''s action items','Staff',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-daily-t03','rt-daily','Lead-recap → Neo Drafts (never auto-sends)','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-daily-t04','rt-daily','Verify the intent pipeline ran today','Staff',4,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-weekly','Weekly Ops (all clients)','Weekly',90,'weekly','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-weekly-t01','rt-weekly','Vendasta check: social calendar + reviews + citations (pull via API)','Staff',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-weekly-t02','rt-weekly','Weekly LEADS recap (leads + pixel + Top-5 prospects + calls)','Staff',2,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-weeklyemail','Weekly Recap Email','Weekly',95,'weekly','weekly_email',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-weeklyemail-t01','rt-weeklyemail','Run /weekly-emails harness (roster = client_services)','Robbie',1,'weekly_email');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-weeklyemail-t02','rt-weeklyemail','Review/elevate drafts; gate on a sample before push','Robbie',2,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-monthly-report','Monthly Report','Monthly',100,'monthly','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t01','rt-monthly-report','Run /full_report for the client','Staff',1,'full_report');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t02','rt-monthly-report','Run /contact_events ledger for the period','Staff',2,'contact_events');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t03','rt-monthly-report','Attach Vendasta premium reports (Reviews + Social Usage + Web Chat) — Vendasta clients','Staff',3,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t04','rt-monthly-report','GBP monthly pulse (calls/directions/clicks trend, reviews, completeness)','Staff',4,'gbp');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t05','rt-monthly-report','Apply /mpgstyle · NO dollar figures · EngageEngine™ tag · ''Powered by EngageEngine™''','Robbie',5,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-monthly-report-t06','rt-monthly-report','Deliver the report to the client','Robbie',6,'');
INSERT INTO sprint_templates (id,name,category,sort_order,cadence,applies_when,is_routine) VALUES ('rt-rediagnose','Re-Diagnose (loop back)','Monthly',110,'monthly','',1);
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-rediagnose-t01','rt-rediagnose','Re-run /ads-audit + DVS + /demand-collapse-diagnostic','Robbie',1,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-rediagnose-t02','rt-rediagnose','Diff vs the Phase-1 baseline and last cycle','Robbie',2,'');
INSERT INTO sprint_template_tasks (id,template_id,notes,assigned_to_role,sort_order,tool_key) VALUES ('rt-rediagnose-t03','rt-rediagnose','Optimize (pause losers, reallocate, new creative) → feed the next build sprint','Robbie',3,'');
